const raceChinese = ["條頓", "羅馬", "高盧", "匈奴", "埃及"];
const raceInfo = {
  條頓: {
    bestConfiguration: {
      infantryNo1Numbers: "1棒",
      infantryNo1ArmorLevel: 7,
      infantryNo2Numbers: "1斧",
      infantryNo2ArmorLevel: 7,
      cavalryNo1Numbers: "1條",
      cavalryNo1ArmorLevel: 11,
      cavalryNo2Numbers: "-",
      cavalryNo2ArmorLevel: "-",
      cavalryNo3Numbers: "-",
      cavalryNo3ArmorLevel: "-",
      Academy: 72055,
      ArmorField: 54935,
      Rd: 13240,
      ArmorLvUp: 298955,
      total: 439185,
      winery: 8,
      advantage: "前期無損啟動成本最低",
      weakness: "會被斧頭拖累速度",
    },
    otherConfiguration: [
      {
        infantryNo1Numbers: "2棒",
        infantryNo1ArmorLevel: 8,
        infantryNo2Numbers: "1斧",
        infantryNo2ArmorLevel: 7,
        cavalryNo1Numbers: "1條",
        cavalryNo1ArmorLevel: 7,
        cavalryNo2Numbers: "-",
        cavalryNo2ArmorLevel: "-",
        cavalryNo3Numbers: "-",
        cavalryNo3ArmorLevel: "-",
        Academy: 72055,
        ArmorField: 24160,
        Rd: 13240,
        ArmorLvUp: 220540,
        winery: 0,
        total: 329995,
        advantage: "會微損但啟動成本極低",
        weakness: "遇到1熊/鱷/虎 死1棒 ; 一樣面臨被斧頭拖累速度問題",
      },
      {
        infantryNo1Numbers: "1棒",
        infantryNo1ArmorLevel: 12,
        infantryNo2Numbers: "-",
        infantryNo2ArmorLevel: "-",
        cavalryNo1Numbers: "1條",
        cavalryNo1ArmorLevel: 17,
        cavalryNo2Numbers: "-",
        cavalryNo2ArmorLevel: "-",
        cavalryNo3Numbers: "-",
        cavalryNo3ArmorLevel: "-",
        Academy: 72055,
        ArmorField: 254825,
        Rd: 9640,
        ArmorLvUp: 479600,
        winery: 20,
        total: 816120,
        advantage: "不帶斧頭速度會更快，總波數需求更低，後期最佳配置",
        weakness: "釀酒20非常貴，適合成形後採用",
      },
    ],
  },
  羅馬: {
    bestConfiguration: {
      infantryNo1Numbers: "-",
      infantryNo1ArmorLevel: "-",
      infantryNo2Numbers: "-",
      infantryNo2ArmorLevel: "-",
      cavalryNo1Numbers: "1帝馬",
      cavalryNo1ArmorLevel: 0,
      cavalryNo2Numbers: "1將軍",
      cavalryNo2ArmorLevel: 0,
      cavalryNo3Numbers: "-",
      cavalryNo3ArmorLevel: "-",
      Academy: 72055,
      ArmorField: 4270,
      Rd: 22680,
      ArmorLvUp: 0,
      winery: "-",
      total: 99005,
      advantage: "不需要升級兵工廠等級",
      weakness: "兵力本身造價昂貴，即使純馬跑的速度也不算快",
    },
  },
  高盧: {
    bestConfiguration: {
      infantryNo1Numbers: "-",
      infantryNo1ArmorLevel: "-",
      infantryNo2Numbers: "-",
      infantryNo2ArmorLevel: "-",
      cavalryNo1Numbers: "1雷法",
      cavalryNo1ArmorLevel: 13,
      cavalryNo2Numbers: "1海頓",
      cavalryNo2ArmorLevel: 12,
      cavalryNo3Numbers: "-",
      cavalryNo3ArmorLevel: "-",
      Academy: 72055,
      ArmorField: 92490,
      Rd: 19120,
      ArmorLvUp: 495070,
      winery: "-",
      total: 678735,
      advantage: "純馬速度算中等",
      weakness: "高盧本身就是缺點。",
    },
  },
  匈奴: {
    bestConfiguration: {
      infantryNo1Numbers: "-",
      infantryNo1ArmorLevel: "-",
      infantryNo2Numbers: "-",
      infantryNo2ArmorLevel: "-",
      cavalryNo1Numbers: "1草騎",
      cavalryNo1ArmorLevel: 18,
      cavalryNo2Numbers: "1神射",
      cavalryNo2ArmorLevel: 18,
      cavalryNo3Numbers: "-",
      cavalryNo3ArmorLevel: "-",
      Academy: 4425,
      ArmorField: 119475,
      Rd: 12390,
      ArmorLvUp: 503050,
      total: 639340,
      winery: 0,
      advantage: "每一波的造兵成本較低，移動速度則是最快，可以有最大刷圈。",
      weakness: "成形成本相對高一點，但是瑕不掩瑜。",
    },
    otherConfiguration: [
      {
        infantryNo1Numbers: "-",
        infantryNo1ArmorLevel: "-",
        infantryNo2Numbers: "-",
        infantryNo2ArmorLevel: "-",
        cavalryNo1Numbers: "1草騎",
        cavalryNo1ArmorLevel: 6,
        cavalryNo2Numbers: "-",
        cavalryNo2ArmorLevel: "-",
        cavalryNo3Numbers: "1掠奪",
        cavalryNo3ArmorLevel: 6,
        Academy: 72055,
        ArmorField: 13230,
        Rd: 16790,
        ArmorLvUp: 123270,
        winery: 0,
        total: 225345,
        advantage: "開刷的成形成本非常低",
        weakness:
          "波數超過一定後生產成本遠大於雙18，同時跑的速度會被掠奪者所拖累。",
      },
    ],
  },
  埃及: {
    bestConfiguration: {
      infantryNo1Numbers: "-",
      infantryNo1ArmorLevel: "-",
      infantryNo2Numbers: "-",
      infantryNo2ArmorLevel: "-",
      cavalryNo1Numbers: "-",
      cavalryNo1ArmorLevel: "-",
      cavalryNo2Numbers: "-",
      cavalryNo2ArmorLevel: "-",
      cavalryNo3Numbers: "-",
      cavalryNo3ArmorLevel: "-",
      Academy: 0,
      ArmorField: 0,
      Rd: 0,
      ArmorLvUp: 0,
      total: 0,
      winery: 0,
      advantage: "選埃及還想刷綠洲是你個人的優點",
      weakness: "選埃及",
    },
  },
};

export { raceChinese, raceInfo };
